# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aae3baf5819a081397479e525dc890c04fef9c3080a39a4edaa7080725d8d1dcb69a7165dbf08b02e82daa65ffd8b71bb6d407d89fb1a7a8c22fe9e0a00edc4

test:
  secret_key_base: a0c7f7d103320e5f3e336edef779aeaf44e4ade1cc73b29f65723c8d6bd819203a95b9217bf9ecb411a266c9bab93f7268158561c2eaf9804b2fa04807e4a21c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
